### PR TITLE
update SVTPlay downloader

### PR DESCRIPTION
**Pull request by vladrich**
Seems like SVTPlay has moved things around again. Would appreciate if someone else could test too.

### CODE REVIEW

**Comment by karjonas** [comment]
Can you provide any example where the previous version does not work?

**Comment by vladrich** [comment]
http://www.svtplay.se/video/9244933/arkitekturens-parlor/arkitekturens-parlor-sasong-4-radhustillbyggnaden-goteborg

**Comment by karjonas** [comment]
That link works fine for me. What error do you get? Can you run with --debug flag and post your output please?

**Comment by vladrich** [comment]
Hm. It works for me now too. Weird. I was seeing failures due to the json request returning 301 and a whole new setup behind that. Maybe SVT is doing A/B testing? 

Anyway, we can leave everything as is for now then. Thanks.

**Comment by njtaylor** [comment]
THanks for the update.

**Comment by karjonas** [comment]
@njtaylor This PR is incorrect and breaks the plugin. Please revert it.

**Comment by njtaylor** [comment]
Should be back to the way it was.

**Pull request merged**
